/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'al9kr5' at '24.01.16 23:03' with Gradle 2.2.1
 *
 * @author al9kr5, @date 24.01.16 23:03
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
